import { Category, Product, Combo, DeliveryZone, Order } from '@/types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'Sparklers',
    slug: 'sparklers',
    description: 'Electric, Gold & Color Sparklers',
    icon_name: 'Sparkles',
    display_order: 1,
    is_active: true,
  },
  {
    id: 'cat-2',
    name: 'Flower Pots',
    slug: 'flower-pots',
    description: 'Golden & multicolor fountains',
    icon_name: 'Flame',
    display_order: 2,
    is_active: true,
  },
  {
    id: 'cat-3',
    name: 'Ground Chakkaras',
    slug: 'ground-chakkaras',
    description: 'High-speed spinning wheels',
    icon_name: 'Disc',
    display_order: 3,
    is_active: true,
  },
  {
    id: 'cat-4',
    name: 'Rockets',
    slug: 'rockets',
    description: 'Whistling & Sky Rockets',
    icon_name: 'Rocket',
    display_order: 4,
    is_active: true,
  },
  {
    id: 'cat-5',
    name: 'Aerial Multi-Shots',
    slug: 'aerial-shots',
    description: '12, 30 & 60 Shot Sky Cakes',
    icon_name: 'Zap',
    display_order: 5,
    is_active: true,
  },
  {
    id: 'cat-6',
    name: 'Sound Crackers',
    slug: 'sound-crackers',
    description: '100 to 10,000 Garland Crackers',
    icon_name: 'Volume2',
    display_order: 6,
    is_active: true,
  },
  {
    id: 'cat-7',
    name: 'Festival Combos',
    slug: 'combos',
    description: 'Curated value gift boxes',
    icon_name: 'Gift',
    display_order: 7,
    is_active: true,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  // Sparklers
  {
    id: 'prod-1',
    category_id: 'cat-1',
    name: '10cm Electric Sparklers',
    slug: '10cm-electric-sparklers',
    sku: 'SPK-10E',
    description: 'Bright electric silver sparks, safe for children.',
    pack_size: '10 Pcs/Box',
    mrp: 200,
    selling_price: 150,
    image_url: '/images/sparkler_box.png',
    is_active: true,
    is_featured: true,
    is_best_seller: true,
    sound_level: 'Silent',
    stock: 250,
  },
  {
    id: 'prod-2',
    category_id: 'cat-1',
    name: '15cm Green & Red Sparklers',
    slug: '15cm-color-sparklers',
    sku: 'SPK-15C',
    description: 'Vibrant dual-color glowing sparklers.',
    pack_size: '10 Pcs/Box',
    mrp: 320,
    selling_price: 240,
    image_url: '/images/sparkler_box.png',
    is_active: true,
    is_featured: false,
    is_best_seller: true,
    sound_level: 'Silent',
    stock: 180,
  },
  {
    id: 'prod-3',
    category_id: 'cat-1',
    name: '30cm Giant Crackling Sparklers',
    slug: '30cm-giant-sparklers',
    sku: 'SPK-30G',
    description: 'Extra long celebration crackling sparklers.',
    pack_size: '5 Pcs/Box',
    mrp: 450,
    selling_price: 330,
    image_url: '/images/sparkler_box.png',
    is_active: true,
    is_featured: true,
    is_best_seller: false,
    sound_level: 'Low',
    stock: 120,
  },

  // Flower Pots
  {
    id: 'prod-4',
    category_id: 'cat-2',
    name: 'Flower Pot Big Deluxe',
    slug: 'flower-pot-big-deluxe',
    sku: 'FPT-BIG',
    description: 'Classic high fountain projecting golden showers up to 10ft.',
    pack_size: '10 Pcs/Box',
    mrp: 650,
    selling_price: 480,
    image_url: '/images/flower_pot.png',
    is_active: true,
    is_featured: true,
    is_best_seller: true,
    sound_level: 'Low',
    stock: 140,
  },
  {
    id: 'prod-5',
    category_id: 'cat-2',
    name: 'Tri-Color Fountain Special',
    slug: 'tri-color-fountain-special',
    sku: 'FPT-TRI',
    description: 'Sequenced red, green, and silver fountain eruption.',
    pack_size: '5 Pcs/Box',
    mrp: 800,
    selling_price: 590,
    image_url: '/images/flower_pot.png',
    is_active: true,
    is_featured: true,
    is_best_seller: false,
    sound_level: 'Low',
    stock: 90,
  },

  // Ground Chakkaras
  {
    id: 'prod-6',
    category_id: 'cat-3',
    name: 'Chakkara Special Big',
    slug: 'chakkara-special-big',
    sku: 'CHK-BIG',
    description: 'Fast rotating ground wheel with golden fiery output.',
    pack_size: '10 Pcs/Box',
    mrp: 400,
    selling_price: 290,
    image_url: '/images/sparkler_box.png',
    is_active: true,
    is_featured: false,
    is_best_seller: true,
    sound_level: 'Low',
    stock: 210,
  },
  {
    id: 'prod-7',
    category_id: 'cat-3',
    name: 'Whistling Spinner Wheel',
    slug: 'whistling-spinner-wheel',
    sku: 'CHK-WHS',
    description: 'Spinning ground wheel with whistling sound.',
    pack_size: '5 Pcs/Box',
    mrp: 520,
    selling_price: 380,
    image_url: '/images/sparkler_box.png',
    is_active: true,
    is_featured: false,
    is_best_seller: false,
    sound_level: 'Medium',
    stock: 95,
  },

  // Rockets
  {
    id: 'prod-8',
    category_id: 'cat-4',
    name: 'Lunik 3-in-1 Sky Rocket',
    slug: 'lunik-3in1-sky-rocket',
    sku: 'RKT-LNK',
    description: 'Ascends 100 feet in the sky before exploding into color stars.',
    pack_size: '10 Pcs/Box',
    mrp: 750,
    selling_price: 540,
    image_url: '/images/aerial_shot.png',
    is_active: true,
    is_featured: true,
    is_best_seller: true,
    sound_level: 'High',
    stock: 130,
  },

  // Aerial Multi-Shots
  {
    id: 'prod-9',
    category_id: 'cat-5',
    name: '12 Shots Fancy Aerial Display',
    slug: '12-shots-fancy-display',
    sku: 'ARS-12F',
    description: 'Sequential 12 sky shots featuring palm tree stars.',
    pack_size: '1 Box',
    mrp: 1200,
    selling_price: 890,
    image_url: '/images/aerial_shot.png',
    is_active: true,
    is_featured: true,
    is_best_seller: true,
    sound_level: 'High',
    stock: 75,
  },
  {
    id: 'prod-10',
    category_id: 'cat-5',
    name: '30 Shots Sky Thunder Symphony',
    slug: '30-shots-sky-thunder',
    sku: 'ARS-30T',
    description: 'Grand celebration cake with 30 rapid-fire multicolor bursts.',
    pack_size: '1 Box',
    mrp: 2800,
    selling_price: 1990,
    image_url: '/images/aerial_shot.png',
    is_active: true,
    is_featured: true,
    is_best_seller: true,
    sound_level: 'High',
    stock: 40,
  },

  // Sound Crackers
  {
    id: 'prod-11',
    category_id: 'cat-6',
    name: '1000 Wala Garland Crackers',
    slug: '1000-wala-garland',
    sku: 'SND-1K',
    description: 'Authentic 1000 long continuous loud sound cracker garland.',
    pack_size: '1 Box',
    mrp: 1100,
    selling_price: 790,
    image_url: '/images/combo_box.png',
    is_active: true,
    is_featured: false,
    is_best_seller: true,
    sound_level: 'High',
    stock: 85,
  },
];

export const INITIAL_COMBOS: Combo[] = [
  {
    id: 'combo-1',
    name: 'Family Celebration Grand Box',
    slug: 'family-celebration-grand-box',
    description: 'Complete family pack with 15 varieties including sparklers, pots, chakkaras, rockets, and 12-shot aerial cake.',
    price: 3490,
    mrp: 5200,
    image_url: '/images/combo_box.png',
    is_active: true,
  },
  {
    id: 'combo-2',
    name: 'Kids Delight Sparkle Pack',
    slug: 'kids-delight-sparkle-pack',
    description: 'Child-friendly assortment with low-noise sparklers, flower pots, spinning wheels, and colorful torches.',
    price: 1890,
    mrp: 2800,
    image_url: '/images/combo_box.png',
    is_active: true,
  },
];

export const INITIAL_DELIVERY_ZONES: DeliveryZone[] = [
  {
    id: 'zone-1',
    zone_name: 'TN (Home Zone)',
    state_codes: ['TN', 'Tamil Nadu'],
    min_order_amount: 3000,
    delivery_fee: 0,
    estimated_days: '2-3 Days',
    is_active: true,
  },
  {
    id: 'zone-2',
    zone_name: 'South India (KL, KA, AP, TS)',
    state_codes: ['PY', 'KL', 'KA', 'AP', 'TS', 'Puducherry', 'Kerala', 'Karnataka', 'Andhra Pradesh', 'Telangana'],
    min_order_amount: 4000,
    delivery_fee: 150,
    estimated_days: '3-4 Days',
    is_active: true,
  },
  {
    id: 'zone-3',
    zone_name: 'Rest of India',
    state_codes: ['ALL', 'MH', 'DL', 'GJ', 'RJ', 'UP', 'WB', 'MP'],
    min_order_amount: 5000,
    delivery_fee: 250,
    estimated_days: '5-7 Days',
    is_active: true,
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-1001',
    order_number: 'VPP-2026-1001',
    customer_name: 'Karthik Subramanian',
    customer_mobile: '9840123456',
    customer_email: 'karthik@example.com',
    shipping_address: 'Door 14, 2nd Cross Street, Anna Nagar',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600040',
    subtotal: 3650,
    discount_amount: 0,
    delivery_fee: 0,
    grand_total: 3650,
    status: 'CONFIRMED',
    admin_notes: 'Customer requested packed dispatch before weekend.',
    created_at: '2026-08-06T14:30:00Z',
    updated_at: '2026-08-06T15:00:00Z',
    items: [
      {
        product_id: 'prod-4',
        product_name: 'Flower Pot Big Deluxe',
        unit_price: 480,
        quantity: 3,
        total_price: 1440,
      },
      {
        product_id: 'prod-9',
        product_name: '12 Shots Fancy Aerial Display',
        unit_price: 890,
        quantity: 2,
        total_price: 1780,
      },
      {
        product_id: 'prod-1',
        product_name: '10cm Electric Sparklers',
        unit_price: 150,
        quantity: 2,
        total_price: 300,
      },
    ],
  },
  {
    id: 'ord-1002',
    order_number: 'VPP-2026-1002',
    customer_name: 'Ananya Rao',
    customer_mobile: '9886012345',
    customer_email: 'ananya.rao@example.com',
    shipping_address: '45/1 Indiranagar 100ft Road',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560038',
    subtotal: 4860,
    discount_amount: 200,
    delivery_fee: 150,
    grand_total: 4810,
    status: 'PACKING',
    admin_notes: 'Paid via UPI reference #98124.',
    created_at: '2026-08-07T08:15:00Z',
    updated_at: '2026-08-07T09:00:00Z',
    items: [
      {
        product_id: 'prod-10',
        product_name: '30 Shots Sky Thunder Symphony',
        unit_price: 1990,
        quantity: 2,
        total_price: 3980,
      },
      {
        product_id: 'prod-5',
        product_name: 'Tri-Color Fountain Special',
        unit_price: 590,
        quantity: 1,
        total_price: 590,
      },
      {
        product_id: 'prod-3',
        product_name: '30cm Giant Crackling Gold Sparklers',
        unit_price: 330,
        quantity: 1,
        total_price: 330,
      },
    ],
  },
];
